export type IValidateUser = {
  customerKey: number;
  mobile: string;
  hasFactor: boolean;
  address: string;
  birthDate: null | Date;
  firstName: null | string;
  lastName: string;
  provinceID: number;
  cityID: number;
  job: null | string;
  followCommission: number;
  buyPriceInYear: number;
  customerZone: null | string;
  marriageDate: null | Date;
  sexuality: boolean;
  usedCreditPrice: number;
  tell: null | string;
  title: null | string;
  nextLevelPrice: number;
  partnerShipCode: null | string;
  customerGroupName: null | string;
  zipCode: null | string;
  nationalCode: null | string;
  educationDegree: null | string;
  inviteTypeID: number;
  partnerBirthDate: null | Date;
  postalCode: null | string;
  token: string | null;
};
